"""razorpay_subscription migration

Revision ID: 052f6a4d9773
Revises: 0ad78a5d8ffa
Create Date: 2026-05-19 16:46:58.729616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '052f6a4d9773'
down_revision: Union[str, Sequence[str], None] = '0ad78a5d8ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('razorpay_signature', sa.String(length=255), nullable=True))
    op.drop_column('subscriptions', 'stripe_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_session_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('subscriptions', 'razorpay_signature')
    op.drop_column('subscriptions', 'razorpay_payment_id')
    op.drop_column('subscriptions', 'razorpay_order_id')
    # ### end Alembic commands ###
