"""razorpay columns

Revision ID: 0ad78a5d8ffa
Revises: b1d7d8be8230
Create Date: 2026-05-19 15:48:04.743893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ad78a5d8ffa'
down_revision: Union[str, Sequence[str], None] = 'b1d7d8be8230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('razorpay_signature', sa.String(length=500), nullable=True))
    op.drop_index(op.f('stripe_session_id'), table_name='payments')
    op.create_unique_constraint(None, 'payments', ['razorpay_order_id'])
    op.drop_column('payments', 'payment_intent_id')
    op.drop_column('payments', 'stripe_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_session_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('payments', sa.Column('payment_intent_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'payments', type_='unique')
    op.create_index(op.f('stripe_session_id'), 'payments', ['stripe_session_id'], unique=True)
    op.drop_column('payments', 'razorpay_signature')
    op.drop_column('payments', 'razorpay_payment_id')
    op.drop_column('payments', 'razorpay_order_id')
    # ### end Alembic commands ###
