"""add created_at to subscriptions

Revision ID: 0be8d054dd87
Revises: c2a03920a032
Create Date: 2026-05-08 13:21:56.836250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0be8d054dd87'
down_revision: Union[str, Sequence[str], None] = 'c2a03920a032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('subscriptions', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('start_date', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.drop_column('subscriptions', 'created_at')
    # ### end Alembic commands ###
