"""add access type

Revision ID: ccb4f28b2b11
Revises: f60a4dea7426
Create Date: 2026-05-19 12:22:44.634244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb4f28b2b11'
down_revision: Union[str, Sequence[str], None] = 'f60a4dea7426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.add_column('enrollments', sa.Column('access_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'access_type')
    op.drop_column('courses', 'is_premium')
    # ### end Alembic commands ###
