"""coupon course

Revision ID: f60a4dea7426
Revises: 41a142233222
Create Date: 2026-05-19 11:43:05.735776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f60a4dea7426'
down_revision: Union[str, Sequence[str], None] = '41a142233222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'coupons', ['coupon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'coupon_id')
    # ### end Alembic commands ###
