services:

  mysql:
    image: mysql:8
    container_name: eduflow-mysql

    environment:
      MYSQL_ROOT_PASSWORD: Ram.8778
      MYSQL_DATABASE: eduflow

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: eduflow-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - mysql

    restart: always


volumes:
  mysql_data: